on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_ENV: development
  APP_ENVIRONMENT: stage
  API_GATEWAY_HOST: http://152.67.9.249:5173/
  API_URL: http://152.67.9.249:5001/api
  NODE_OPTIONS: --max_old_space_size=4096

name: Deploy Development
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: [self-hosted, eks-runner-fe]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up staging env
        run: |
          echo "VITE_API_URL=${{ env.API_URL }}" >> .env.staging

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: npm install and build
        run: |
          npm install --force
          npm install -g typescript vite
          tsc -b && vite build --mode staging
          ls -larth
          pwd
